/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hopital;

/**
 *
 * @author Prabhash
 */
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.awt.*;
import java.awt.image.BufferedImage;

public class Admin_Login extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Login
     */
    public Admin_Login() {
        initComponents();
    }
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JPasswordField();
        Login_Button = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1031, 490));
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/Image Folder/my10.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setToolTipText("Our Vision");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4);
        jLabel4.setBounds(610, 260, 260, 250);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Username");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(90, 330, 80, 15);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Password");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(90, 370, 63, 21);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Login Details");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(120, 280, 114, 24);

        usernametxt.setToolTipText("Enter Username");
        usernametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernametxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernametxtFocusLost(evt);
            }
        });
        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });
        jPanel3.add(usernametxt);
        usernametxt.setBounds(170, 320, 159, 30);

        passwordtxt.setToolTipText("Enter Password");
        passwordtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordtxtKeyPressed(evt);
            }
        });
        jPanel3.add(passwordtxt);
        passwordtxt.setBounds(170, 370, 159, 30);

        Login_Button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Login_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/Image Folder/Apps-preferences-system-login-icon.png"))); // NOI18N
        Login_Button.setText("Login");
        Login_Button.setToolTipText("Login");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(Login_Button);
        Login_Button.setBounds(130, 420, 87, 24);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/Image Folder/sign-up-icon.png"))); // NOI18N
        jButton6.setText("Sign Up");
        jButton6.setToolTipText("Sign-Up");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(260, 420, 100, 24);

        jButton1.setText("Forgot Password");
        jButton1.setToolTipText("Reset Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(160, 470, 159, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/Image Folder/hospial name.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 930, 240);

        wall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/Image Folder/aero_blue_24-wallpaper-960x600.jpg"))); // NOI18N
        jPanel3.add(wall);
        wall.setBounds(0, 240, 930, 290);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 930, 530);

        setSize(new java.awt.Dimension(947, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private Image ScaledImage(Image img, int w, int h){
        BufferedImage  resizedImage = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, w, h, null);
        g2.dispose();
        return resizedImage;
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        new forgotten_password().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");
            PreparedStatement pst1=con.prepareStatement("SELECT * FROM login WHERE username=? AND password=?");
            pst1.setString(1,usernametxt.getText());
            pst1.setString(2,passwordtxt.getText());
            ResultSet rs1=pst1.executeQuery();
            if(rs1.next()){
                close();
                new Working_Page().setVisible(true);

            }
            else{
                JOptionPane.showMessageDialog(null,"Invalid Username or Password");
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,""+e);
        }
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed

    private void passwordtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordtxtKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");
                PreparedStatement pst1=con.prepareStatement("SELECT * FROM login WHERE username=? AND password=?");
                pst1.setString(1,usernametxt.getText());
                pst1.setString(2,passwordtxt.getText());
                ResultSet rs1=pst1.executeQuery();
                if(rs1.next()){
                    close();
                    new Working_Page().setVisible(true);

                }
                else{
                    JOptionPane.showMessageDialog(null,"Invalid Username or Password");
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,""+e);
            }
        }
    }//GEN-LAST:event_passwordtxtKeyPressed

    private void usernametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernametxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtFocusLost

    private void usernametxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernametxtFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usernametxtFocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        close();
        new Sign_up().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        close();
        new Our_vision().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_Button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JTextField usernametxt;
    private javax.swing.JLabel wall;
    // End of variables declaration//GEN-END:variables
}
