/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hopital;

/**
 *
 * @author Prabhash
 */
import java.awt.event.*;
import java.awt.*;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.GregorianCalendar;
public class Billing_form extends javax.swing.JFrame {

    /**
     * Creates new form Billing_form
     */
    public Billing_form() {
        initComponents();
        CurrentDate();
        Fillcombo();
        Fillcomboid();
        //FilledListBox();
    }
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    public void CurrentDate(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int year = cal.get(Calendar.YEAR);
        jLabel7.setText(day+"/"+(month+1)+"/"+year);
        
    }
    /*private void FilledListBox(){
        DefaultListModel m = new DefaultListModel();
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");
            String sql = "SELECT * FROM bill";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                //String List = rs.getString("patient_id");
                m.addElement(rs.getString("patient_id"));
                m.addElement(rs.getString("room_charge"));
                m.addElement(rs.getString("medi_charge"));
                m.addElement(rs.getString("treat_charge"));
                m.addElement(rs.getString("test_charge"));
                m.addElement(rs.getString("mis_charge"));
            }
            //jList1.setModel(m);
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }*/
    private void Fillcombo() {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");
            String sql = "SELECT * FROM patient";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("pat_name");
                pat_name_combo.addItem(name);
            }
        } catch (ClassNotFoundException | SQLException E) {
            JOptionPane.showMessageDialog(null, E);
        }
    }
    private void Fillcomboid() {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");
            String sql = "SELECT * FROM patient";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String id = rs.getString("pat_id");
                patient_id_combo.addItem(id);
            }
        } catch (ClassNotFoundException | SQLException E) {
            JOptionPane.showMessageDialog(null, E);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        discharge = new javax.swing.JLabel();
        dod = new com.toedter.calendar.JDateChooser();
        doatxt = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        Doa = new javax.swing.JLabel();
        room = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Room = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        medi = new javax.swing.JTextField();
        treat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mis = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        test = new javax.swing.JTextField();
        pat_name_combo = new javax.swing.JComboBox();
        patient_id_combo = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        pat_type = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Patient_name_bill = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Room1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        bill_room = new javax.swing.JLabel();
        bill_medi = new javax.swing.JLabel();
        bill_treat = new javax.swing.JLabel();
        bill_test = new javax.swing.JLabel();
        bill_misc = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bill_no = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        payment = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        signout = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Billing Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        discharge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        discharge.setText("Date of Discharge");

        dod.setDateFormatString("dd/MMM/yyyy");

        doatxt.setDateFormatString("dd/MMM/yyyy");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Patient Name");

        Doa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Doa.setText("Date of Addmission");

        room.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                roomKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Patient ID");

        Room.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Room.setText("Room Charges");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Medicine Charges");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Treatment Charges");

        medi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mediKeyTyped(evt);
            }
        });

        treat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                treatKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Miscellaneous");

        mis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                misKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Test Charges");

        test.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                testKeyTyped(evt);
            }
        });

        pat_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                pat_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        pat_name_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pat_name_comboActionPerformed(evt);
            }
        });

        patient_id_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                patient_id_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Patient Type");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Doa)
                        .addComponent(jLabel1)
                        .addComponent(discharge)
                        .addComponent(Room)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel2))
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(patient_id_combo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mis, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(test)))
                            .addComponent(pat_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pat_type, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dod, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medi, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(treat, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(patient_id_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pat_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(pat_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Doa)
                    .addComponent(doatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(discharge)
                    .addComponent(dod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room)
                    .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(treat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1);
        jPanel1.setBounds(60, 40, 350, 490);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        Patient_name_bill.setEditable(false);

        jLabel9.setText("Total Payment:");

        jLabel10.setText("Signature:");

        jLabel12.setText("Patient Name:");

        Total.setEditable(false);
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        Room1.setText("Room Charges:");

        jLabel11.setText("Medicine :");

        jLabel16.setText("Treatment :");

        jLabel17.setText("Test :");

        jLabel18.setText("Miscellaneous :");

        jLabel24.setText("------------------------------------------------------------------------");

        jLabel6.setText("Date:");

        jLabel7.setText("Date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Room1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bill_room, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bill_medi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bill_treat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bill_test, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bill_misc, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Room1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(bill_room, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(bill_medi, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(bill_treat, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(bill_test, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(bill_misc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jLabel5.setText("Bill Number:");

        jLabel14.setText("Rs");

        bill_no.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 102, 255));
        jLabel19.setText("WELLSTONE HOSPITAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Patient_name_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bill_no, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bill_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Patient_name_bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(25, 25, 25))
        );

        jPanel4.add(jPanel3);
        jPanel3.setBounds(520, 50, 373, 520);

        payment.setText("Pay");
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });
        jPanel4.add(payment);
        payment.setBounds(100, 540, 74, 23);

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel4.add(Clear);
        Clear.setBounds(290, 540, 65, 23);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/back-icon.png"))); // NOI18N
        Back.setText("Back");
        Back.setToolTipText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel4.add(Back);
        Back.setBounds(775, 10, 75, 20);

        signout.setText("Log out");
        signout.setToolTipText("Log out");
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });
        jPanel4.add(signout);
        signout.setBounds(860, 10, 69, 20);

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setText("X");
        close.setToolTipText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel4.add(close);
        close.setBounds(940, 10, 60, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1031, 619));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        //Pat_id_txt.setText("");
        patient_id_combo.setSelectedItem("");
        pat_name_combo.setSelectedItem("");
        ((JTextField)doatxt.getDateEditor().getUiComponent()).setText("");
        ((JTextField)dod.getDateEditor().getUiComponent()).setText("");
        room.setText("");
        medi.setText("");
        treat.setText("");
        test.setText("");
        mis.setText("");
        Patient_name_bill.setText("");
        bill_room.setText("");
        bill_medi.setText("");
        bill_treat.setText("");
        bill_test.setText("");
        bill_misc.setText("");
        bill_no.setText("");
        Patient_name_bill.setText("");
        Total.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");
            String sql1 = "INSERT INTO bill(patient_id,date_discharge,room_charge,medi_charge,treat_charge,test_charge,mis_charge) VALUES(?,?,?,?,?,?,?)";
            //String sql1 = "INSERT INTO bill(patient_id,date_discharge,medi_charge,treat_charge,test_charge,mis_charge) VALUES(?,?,?,?,?,?,?)";
            PreparedStatement pst1 = con.prepareStatement(sql1);
            //pst1.setString(1,Pat_id_txt.getText());
            pst1.setString(1, (String) patient_id_combo.getSelectedItem());
            pst1.setString(2,((JTextField)dod.getDateEditor().getUiComponent()).getText());
            pst1.setString(3,room.getText());
            pst1.setString(4,medi.getText());
            pst1.setString(5,treat.getText());
            pst1.setString(6,test.getText());
            pst1.setString(7,mis.getText());
            ///
            //Date date1 = (Date) doatxt.getDate();
            //Date date2 = (Date) dod.getDate(); 
            //long differenceInMilliseconds = date2.getTime() - date1.getTime();
            //int differenceInDays = (int)differenceInMilliseconds/(1000*60*60*24);
            //PreparedStatement pst9 = con.prepareStatement("SELECT price_per_day FROM patient INNER JOIN room ON patient.room_type=room.room_type and patient.pat_id=?;");
            //pst9.setString(1, (String) patient_id_combo.getSelectedItem());
            //ResultSet rs9 = pst9.executeQuery();
            //int x = rs9.getInt("price_per_day");
            //room.setText(String.valueOf(differenceInDays*x));
            ///
            
            pst1.executeQuery();
            JOptionPane.showMessageDialog(null,"Added to Bill");
            /////
            String sql2 = "UPDATE bill SET total=room_charge+medi_charge+treat_charge+test_charge+mis_charge WHERE patient_id=?";
            PreparedStatement pst2 = con.prepareStatement(sql2);
            pst2.setString(1, (String) patient_id_combo.getSelectedItem());
            ResultSet rs2 = pst2.executeQuery();
            if(rs2.next()){
                int a = Integer.parseInt(room.getText());
                int b = Integer.parseInt(medi.getText());
                int c = Integer.parseInt(treat.getText());
                int d = Integer.parseInt(test.getText());
                int e = Integer.parseInt(mis.getText());
                int sum = a + b + c + d + e;
                Total.setText(String.valueOf(sum));
            }
            PreparedStatement pst3=con.prepareStatement("UPDATE bill SET bill_no = (SELECT test from id) WHERE patient_id=?");
            pst3.setString(1, (String) patient_id_combo.getSelectedItem());
            pst3.executeQuery();
            ////
            PreparedStatement pst4=con.prepareStatement("UPDATE id SET test = test+1 ");
            pst4.executeQuery();
            ////
            PreparedStatement pst5 = con.prepareStatement("SELECT bill_no FROM bill WHERE patient_id=?");
            pst5.setString(1, (String) patient_id_combo.getSelectedItem());
            ResultSet rs5 = pst5.executeQuery();
            if(rs5.next()){
                bill_no.setText(rs5.getString(1));
                JOptionPane.showMessageDialog(null, "Note the bill no.");
            }
            else{
                JOptionPane.showMessageDialog(null,"Patient ID does not Exist!");
            }
            
            String sql9 = "SELECT * FROM bill WHERE PATIENT_ID=?";
            PreparedStatement pst9 = con.prepareStatement(sql9);
            pst9.setString(1, (String) patient_id_combo.getSelectedItem());
            ResultSet rs9 = pst9.executeQuery();
            if(rs9.next()){
                bill_room.setText(rs9.getString("ROOM_CHARGE"));
                bill_medi.setText(rs9.getString("MEDI_CHARGE"));
                bill_treat.setText(rs9.getString("TREAT_CHARGE"));
                bill_test.setText(rs9.getString("TEST_CHARGE"));
                bill_misc.setText(rs9.getString("MIS_CHARGE"));
            }
            else{
                JOptionPane.showMessageDialog(null, "Internal Error Occured");
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_paymentActionPerformed

    private void pat_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_pat_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");
            String temp = (String) pat_name_combo.getSelectedItem();
            String sql = "SELECT * FROM patient WHERE pat_name=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, temp);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                patient_id_combo.setSelectedItem(rs.getString("PAT_ID"));
                Patient_name_bill.setText(rs.getString("PAT_NAME"));
                pat_type.setText(rs.getString("PATIENT_TYPE"));
                doatxt.setDate(rs.getDate("PAT_DOA"));
                if(pat_type.getText().equals("OUT")){
                    room.setText("0");
                    room.setEditable(false);
                }
                else{
                    room.setEditable(true);
                    dod.setDate(rs.getDate("DOD"));
                }
                
                //dod.setDate(rs.getDate("DOD"));
                /*
                //try{
                
                Date date1 = (Date) doatxt.getDate();
                Date date2 = (Date) dod.getDate(); 
                long differenceInMilliseconds = date2.getTime() - date1.getTime();
                int differenceInDays = (int)differenceInMilliseconds/(1000*60*60*24);
                PreparedStatement pst9 = con.prepareStatement("SELECT price_per_day FROM patient INNER JOIN room ON patient.room_type=room.room_type and patient.pat_id=?;");
                pst9.setString(1, (String) patient_id_combo.getSelectedItem());
                ResultSet rs9 = pst9.executeQuery();    
                int x = Integer.parseInt(rs9.getString(1));
                room.setText(String.valueOf(differenceInDays*x));
                //room.setText(differenceInDays*x);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, ex);
                }
                    */
                
                //Patient_name_bill.setText(rs.getString("PAT_NAME"));
                //PAT_NO ,PAT_ID,PAT_NAME,PATIENT_TYPE,PAT_DOA,DOD,PAT_CONTACT	GENDER	AGE,ADDRESS,MEDI,APP_DOC,HISTORY,PROBLEM,ROOM	ROOM_TYPE
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_pat_name_comboPopupMenuWillBecomeInvisible

    private void pat_name_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_name_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pat_name_comboActionPerformed

    private void patient_id_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_patient_id_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");
            String temp = (String) patient_id_combo.getSelectedItem();
            String sql = "SELECT * FROM patient WHERE pat_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, temp);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                pat_name_combo.setSelectedItem(rs.getString("PAT_NAME"));
                
                Patient_name_bill.setText(rs.getString("PAT_NAME"));
                pat_type.setText(rs.getString("PATIENT_TYPE"));
                //PreparedStatement s = con.prepareStatement("SELECT room_type from patient where pat_id=?")
                if(pat_type.getText().equals("OUT")){
                    room.setText("0");
                    room.setEditable(false);
                }
                else{
                    room.setEditable(true);
                }
                doatxt.setDate(rs.getDate("PAT_DOA"));
                dod.setDate(rs.getDate("DOD"));
                Patient_name_bill.setText(rs.getString("PAT_NAME"));
                //PAT_NO ,PAT_ID,PAT_NAME,PATIENT_TYPE,PAT_DOA,DOD,PAT_CONTACT	GENDER	AGE,ADDRESS,MEDI,APP_DOC,HISTORY,PROBLEM,ROOM	ROOM_TYPE
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_patient_id_comboPopupMenuWillBecomeInvisible

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void roomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )){
            evt.consume();
        }
    }//GEN-LAST:event_roomKeyTyped

    private void mediKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mediKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )){
            evt.consume();
        }
    }//GEN-LAST:event_mediKeyTyped

    private void treatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_treatKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )){
            evt.consume();
        }
    }//GEN-LAST:event_treatKeyTyped

    private void testKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_testKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )){
            evt.consume();
        }
    }//GEN-LAST:event_testKeyTyped

    private void misKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_misKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )){
            evt.consume();
        }
    }//GEN-LAST:event_misKeyTyped

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        close();
        new Working_Page().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
        // TODO add your handling code here:
        close();
        new Admin_Login().setVisible(true);
    }//GEN-LAST:event_signoutActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Clear;
    private javax.swing.JLabel Doa;
    private javax.swing.JTextField Patient_name_bill;
    private javax.swing.JLabel Room;
    private javax.swing.JLabel Room1;
    private javax.swing.JTextField Total;
    private javax.swing.JLabel bill_medi;
    private javax.swing.JLabel bill_misc;
    private javax.swing.JTextField bill_no;
    private javax.swing.JLabel bill_room;
    private javax.swing.JLabel bill_test;
    private javax.swing.JLabel bill_treat;
    private javax.swing.JButton close;
    private javax.swing.JLabel discharge;
    private com.toedter.calendar.JDateChooser doatxt;
    private com.toedter.calendar.JDateChooser dod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField medi;
    private javax.swing.JTextField mis;
    private javax.swing.JComboBox pat_name_combo;
    private javax.swing.JTextField pat_type;
    private javax.swing.JComboBox patient_id_combo;
    private javax.swing.JButton payment;
    private javax.swing.JTextField room;
    private javax.swing.JButton signout;
    private javax.swing.JTextField test;
    private javax.swing.JTextField treat;
    // End of variables declaration//GEN-END:variables
}
