/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hopital;

/**
 *
 * @author Prabhash
 */
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.awt.event.*;
import java.awt.*;
import javax.swing.JTextField;
public class Doctor_Details extends javax.swing.JFrame {

    /**
     * Creates new form Doctor_Details
     */
    public Doctor_Details() {
        initComponents();
        //Update_table();
        Fillcombo();
        Fillcombodoc();
    }
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /*
    private void Update_table(){
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");
            
            
            String sql="SELECT doc_id,doc_name,specialzn FROM doctor";
            PreparedStatement pst5=con.prepareStatement(sql);
            ResultSet rs = pst5.executeQuery();
            Doctor_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }*/
    private void Fillcombo(){
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");
            String sql = "SELECT * FROM department";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String Name = rs.getString("dept_name");
                d_dept.addItem(Name);
            }
        }
        catch(ClassNotFoundException | SQLException E){
            JOptionPane.showMessageDialog(null, E);
        }
    }
    
    private void Fillcombodoc(){
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");
            String sql = "SELECT * FROM doctor";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String name = rs.getString("doc_name");
                doc_name_combo.addItem(name);
            }
        }
        catch(ClassNotFoundException | SQLException E){
            JOptionPane.showMessageDialog(null, E);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        special = new javax.swing.JLabel();
        doc_contact_txt = new javax.swing.JTextField();
        doc_name = new javax.swing.JTextField();
        Doc_id = new javax.swing.JLabel();
        doc_cont = new javax.swing.JLabel();
        doc_id_txt = new javax.swing.JTextField();
        doc_dept = new javax.swing.JLabel();
        Doj = new javax.swing.JLabel();
        special_txt = new javax.swing.JTextField();
        doc_name_label = new javax.swing.JLabel();
        d_dept = new javax.swing.JComboBox();
        dojtxt = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        address_textarea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        type_combo = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        Add_doc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        doc_name_combo = new javax.swing.JComboBox();
        Delete = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        qual_txt = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        close = new javax.swing.JButton();
        counter = new javax.swing.JLabel();
        signout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctor Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        special.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        special.setText("Specialization");

        doc_contact_txt.setToolTipText("Contact Number");
        doc_contact_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                doc_contact_txtKeyTyped(evt);
            }
        });

        doc_name.setToolTipText("Name");

        Doc_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Doc_id.setText("Doctor ID");

        doc_cont.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        doc_cont.setText("Contact Number");

        doc_id_txt.setEditable(false);
        doc_id_txt.setToolTipText("Doctor ID");

        doc_dept.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        doc_dept.setText("Department");

        Doj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Doj.setText("Date of Joining");

        special_txt.setToolTipText("Specialization");
        special_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                special_txtActionPerformed(evt);
            }
        });

        doc_name_label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        doc_name_label.setText("Doctor Name");

        d_dept.setEditable(true);
        d_dept.setToolTipText("Department");

        dojtxt.setToolTipText("Date Of Joining");
        dojtxt.setDateFormatString("dd/MMM/yyyy");

        address_textarea.setColumns(20);
        address_textarea.setRows(5);
        address_textarea.setToolTipText("Address");
        jScrollPane2.setViewportView(address_textarea);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Address");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Type");

        type_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Permanent", "Trainee", "Visiting" }));
        type_combo.setToolTipText("Type");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/Actions-edit-clear-icon.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.setToolTipText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Add_doc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/Add-icon.png"))); // NOI18N
        Add_doc.setText("Add");
        Add_doc.setToolTipText("Add");
        Add_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_docActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete/Update Profile\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Doctor Name");

        doc_name_combo.setToolTipText("Search Doctor");
        doc_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                doc_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        doc_name_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_name_comboActionPerformed(evt);
            }
        });

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/delete-1-icon.png"))); // NOI18N
        Delete.setText("Delete");
        Delete.setToolTipText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/App-edit-icon.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.setToolTipText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(doc_name_combo, 0, 158, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(29, 29, 29)
                .addComponent(Delete)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(doc_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Qualification");

        qual_txt.setToolTipText("Qualification");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(Add_doc)
                        .addGap(51, 51, 51)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(special)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(doc_name_label))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(42, 42, 42)
                                            .addComponent(jLabel2))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(Doj))))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doc_name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(special_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dojtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(qual_txt, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doc_cont)
                            .addComponent(doc_dept)
                            .addComponent(jLabel3)
                            .addComponent(Doc_id))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doc_contact_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doc_id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doc_name_label)
                            .addComponent(doc_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doc_cont)
                            .addComponent(doc_contact_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(special)
                            .addComponent(special_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doc_dept)
                            .addComponent(d_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dojtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Doj))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(qual_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(doc_id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Doc_id, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Add_doc)
                            .addComponent(jButton4))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1);
        jPanel1.setBounds(90, 40, 810, 460);

        Back.setText("Back");
        Back.setToolTipText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel3.add(Back);
        Back.setBounds(800, 10, 70, 20);

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setText("X");
        close.setToolTipText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel3.add(close);
        close.setBounds(960, 10, 60, 20);

        counter.setText("jLabel1");
        jPanel3.add(counter);
        counter.setBounds(880, 450, 34, 14);

        signout.setText("Log out");
        signout.setToolTipText("Log out");
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });
        jPanel3.add(signout);
        signout.setBounds(880, 10, 69, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/mb02.png"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 1030, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1047, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        doc_id_txt.setText("");
        doc_name.setText("");
        doc_contact_txt.setText("");
        special_txt.setText("");
        d_dept.setSelectedItem("");
        address_textarea.setText("");
        type_combo.setSelectedItem("");
        qual_txt.setText("");
        //dojtxt.setText("");
        ((JTextField)dojtxt.getDateEditor().getUiComponent()).setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Add_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_docActionPerformed
         try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");
            String sql = "insert into doctor(doc_name,doc_contact,specialzn,doc_dept,doj,address,doc_type,qualification) values (?,?,?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
            //pst.setString(1,doc_id_txt.getText());
            pst.setString(1,doc_name.getText());
            pst.setString(2,doc_contact_txt.getText());
            pst.setString(3,special_txt.getText());
            pst.setString(4,(String)d_dept.getSelectedItem());
            pst.setString(5,((JTextField)dojtxt.getDateEditor().getUiComponent()).getText());
            pst.setString(6,address_textarea.getText());
            pst.setString(7,(String)type_combo.getSelectedItem());
            pst.setString(8,qual_txt.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Added");
            /////
            PreparedStatement pst1=con.prepareStatement("UPDATE doctor SET doc_no = (SELECT doctor from id) WHERE doc_name=? and doc_contact=?");
            pst1.setString(1,doc_name.getText());
            pst1.setString(2,doc_contact_txt.getText());
            pst1.executeQuery();
            ////
            PreparedStatement pst2=con.prepareStatement("UPDATE id SET doctor = doctor+1 ");
            pst2.executeQuery();
            ////
            PreparedStatement pst3=con.prepareStatement("SELECT doc_no FROM doctor WHERE doc_name=? and doc_contact=?");
            pst3.setString(1,doc_name.getText());
            pst3.setString(2,doc_contact_txt.getText());
            ResultSet rs3 = pst3.executeQuery();
            if(rs3.next()){
                counter.setText(rs3.getString(1));
                String sql4 = "Update doctor set doc_id = 'D'||? WHERE doc_name=? and doc_contact=?";
                PreparedStatement pst4=con.prepareStatement(sql4);
                pst4.setString(1,counter.getText());
                pst4.setString(2,doc_name.getText());
                pst4.setString(3,doc_contact_txt.getText());
                pst4.executeQuery();
                
                PreparedStatement pst5=con.prepareStatement("SELECT doc_id FROM doctor WHERE doc_name=? and doc_contact=?");
                pst5.setString(1,doc_name.getText());
                pst5.setString(2,doc_contact_txt.getText());
                ResultSet rs5 = pst5.executeQuery();
                if(rs5.next()){
                    doc_id_txt.setText(rs5.getString(1));
                    //Update_table();
                }
                //JOptionPane.showMessageDialog(null,"Done Everything");
            }
            else{
                JOptionPane.showMessageDialog(null,"Error Occured!");
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_Add_docActionPerformed

    private void special_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_special_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_special_txtActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        close();
        new Doctor_Area().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void doc_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_doc_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");
            String temp = (String)doc_name_combo.getSelectedItem();
            String sql = "SELECT * FROM doctor WHERE doc_name=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, (String) doc_name_combo.getSelectedItem());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                //String add1 = rs.getString("dept_id");
                doc_name.setText(rs.getString("doc_name"));
                doc_id_txt.setText(rs.getString("doc_id"));
                special_txt.setText(rs.getString("specialzn"));
                dojtxt.setDate(rs.getDate("doj"));
                address_textarea.setText(rs.getString("address"));
                doc_contact_txt.setText(rs.getString("doc_contact"));
                qual_txt.setText(rs.getString("qualification"));
                d_dept.setSelectedItem(rs.getString("doc_dept"));
                type_combo.setSelectedItem(rs.getString("DOC_TYPE"));
                
                
                
                
                //PAT_ID	PAT_NAME	CONTACT	GENDER	AGE	PAT_DOA	HISTORY	PROBLEM	ROOM	ADDRESS
            }
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_doc_name_comboPopupMenuWillBecomeInvisible

    private void doc_name_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_name_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_name_comboActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null,"Do you really want to Delete?","Delete",JOptionPane.YES_NO_OPTION);
        if(p == 0)
        {
            try
            {
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");

                PreparedStatement pst=con.prepareStatement("SELECT * FROM doctor WHERE doc_id=?");
                pst.setString(1,doc_id_txt.getText());
                ResultSet rs = pst.executeQuery();
                if(rs.next())
                {
                    PreparedStatement pst1=con.prepareStatement("DELETE FROM doctor WHERE doc_id=?");
                    pst1.setString(1,doc_id_txt.getText());

                    pst1.execute();
                    JOptionPane.showMessageDialog(null,"Deleted");
                    doc_name_combo.setSelectedItem("");
                    //Update_table();
                    Fillcombodoc();
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"No Doctor of such Doctor Id is there");
                    JOptionPane.showMessageDialog(null,"Please check the id and retry");
                }

            }
            catch(ClassNotFoundException | SQLException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");
            
            //String sql = "UPDATE doctor SET(doc_name=?,doc_contact=?,specialzn,doc_dept,doj,address,doc_type,qualification) WHERE doc_id=?";
            String value1 = doc_name.getText();
            String value2 = special_txt.getText();
            String value3 = doc_contact_txt.getText();
            //java.util.Date value4 = dojtxt.getDate();
            String value5 = qual_txt.getText();
            String value6 = address_textarea.getText();
            String value7 = (String) d_dept.getSelectedItem();
            String value8 = (String) type_combo.getSelectedItem();
            
            String sql = "UPDATE doctor SET doc_name='"+value1+"',specialzn='"+value2+"',doc_contact='"+value3+"',doc_dept='"+value7+"',doc_type='"+value8+"',address='"+value6+"',qualification='"+value5+"' WHERE doc_id=?  ";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, doc_id_txt.getText());
            pst.executeQuery();
            PreparedStatement pst1 = con.prepareStatement("UPDATE doctor SET doj=? WHERE doc_id=?");
            pst1.setString(1,((JTextField)dojtxt.getDateEditor().getUiComponent()).getText());
            pst1.setString(2, doc_id_txt.getText());
            pst1.executeQuery();
            JOptionPane.showMessageDialog(null,"Updated");
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
        // TODO add your handling code here:
        close();
        new Admin_Login().setVisible(true);
    }//GEN-LAST:event_signoutActionPerformed

    private void doc_contact_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doc_contact_txtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )){
            evt.consume();
        }
    }//GEN-LAST:event_doc_contact_txtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Doctor_Details().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_doc;
    private javax.swing.JButton Back;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Doc_id;
    private javax.swing.JLabel Doj;
    private javax.swing.JTextArea address_textarea;
    private javax.swing.JButton close;
    private javax.swing.JLabel counter;
    private javax.swing.JComboBox d_dept;
    private javax.swing.JLabel doc_cont;
    private javax.swing.JTextField doc_contact_txt;
    private javax.swing.JLabel doc_dept;
    private javax.swing.JTextField doc_id_txt;
    private javax.swing.JTextField doc_name;
    private javax.swing.JComboBox doc_name_combo;
    private javax.swing.JLabel doc_name_label;
    private com.toedter.calendar.JDateChooser dojtxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField qual_txt;
    private javax.swing.JButton signout;
    private javax.swing.JLabel special;
    private javax.swing.JTextField special_txt;
    private javax.swing.JComboBox type_combo;
    // End of variables declaration//GEN-END:variables
}
