/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hopital;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Prabhash
 */
public class patient_out extends javax.swing.JFrame {

    /**
     * Creates new form patient_out
     */
    public patient_out() {
        initComponents();
        Fillcombodoc();
        Fillcombo();
    }
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    private void Fillcombodoc(){
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");
            String sql = "SELECT * FROM doctor";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String name = rs.getString("doc_name");
                app_doc.addItem(name);
            }
        }
        catch(ClassNotFoundException | SQLException E){
            JOptionPane.showMessageDialog(null, E);
        }
    }
    private void Fillcombo() {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");
            String sql = "SELECT * FROM patient where PATIENT_TYPE='OUT'";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("pat_name");
                pat_name_combo.addItem(name);
            }
        } catch (ClassNotFoundException | SQLException E) {
            JOptionPane.showMessageDialog(null, E);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pat_id_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Pat_id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address_txt = new javax.swing.JTextArea();
        Contact_number = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        pat_name = new javax.swing.JLabel();
        Dob = new javax.swing.JLabel();
        contact_txt = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox();
        Add = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        medi = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        problem = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        app_doc = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rel_name = new javax.swing.JTextField();
        rel_contact = new javax.swing.JTextField();
        app_date = new com.toedter.calendar.JDateChooser();
        pat_name_combo = new javax.swing.JComboBox();
        Delete1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        counter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        pat_id_txt.setEditable(false);
        pat_id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pat_id_txtActionPerformed(evt);
            }
        });

        jLabel2.setText("Appointment Date");

        Gender.setText("Gender");

        Pat_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Pat_id.setText("Patient ID");

        address_txt.setColumns(20);
        address_txt.setRows(5);
        jScrollPane1.setViewportView(address_txt);

        Contact_number.setText("Contact Number");

        address.setText("Address");

        pat_name.setText("Patient Name");

        Dob.setText("Age");

        contact_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_txtActionPerformed(evt);
            }
        });
        contact_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contact_txtKeyTyped(evt);
            }
        });

        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });

        gender.setEditable(true);
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MALE", "FEMALE", "OTHER" }));

        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/Add-icon.png"))); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/Actions-edit-clear-icon.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Ailment");

        jLabel5.setText("Medicine Prescribed");

        medi.setColumns(20);
        medi.setRows(5);
        jScrollPane2.setViewportView(medi);

        problem.setColumns(20);
        problem.setRows(5);
        jScrollPane3.setViewportView(problem);

        jLabel6.setText("Appointed Doctor");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relative Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel7.setText("Name");

        jLabel8.setText("Contact");

        rel_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rel_contactActionPerformed(evt);
            }
        });
        rel_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rel_contactKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(rel_contact))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(rel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rel_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rel_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        app_date.setDateFormatString("dd/MMM/yyyy");

        pat_name_combo.setEditable(true);
        pat_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                pat_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        pat_name_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pat_name_comboActionPerformed(evt);
            }
        });

        Delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/delete-1-icon.png"))); // NOI18N
        Delete1.setText("Delete");
        Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(address)
                            .addComponent(pat_name)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1)
                            .addComponent(pat_name_combo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contact_number, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Gender, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Dob, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pat_id, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contact_txt)
                    .addComponent(age, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(app_doc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pat_id_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(app_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Add)
                        .addGap(18, 18, 18)
                        .addComponent(Delete1)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(pat_name)
                                .addComponent(pat_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(app_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Contact_number)
                            .addComponent(contact_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gender))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dob))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(app_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pat_id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pat_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Add)
                            .addComponent(Delete1)
                            .addComponent(jButton4))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 40, 870, 460);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(770, 10, 70, 20);

        jButton6.setText("Log out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(850, 10, 69, 20);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("X");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(930, 10, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/shutterstock_1137753701.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 520);

        counter.setText("jLabel3");
        jPanel1.add(counter);
        counter.setBounds(950, 490, 34, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1019, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pat_id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pat_id_txtActionPerformed

    private void contact_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_txtActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","india");
            String sql = "insert into patient(PAT_NAME,PAT_DOA,PAT_CONTACT,GENDER,AGE,ADDRESS,MEDI,APP_DOC,PROBLEM,REL_NAME,REL_CONTACT) values (?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
            //pst.setString(1,pat_id_txt.getText());
            //pst.setString(1,pat_name_txt.getText());
            pst.setString(1, (String) pat_name_combo.getSelectedItem());
            pst.setString(2,((JTextField)app_date.getDateEditor().getUiComponent()).getText());
            pst.setString(3,contact_txt.getText());
            pst.setString(4,(String)gender.getSelectedItem());
            pst.setString(5,age.getText());
            pst.setString(6,address_txt.getText());
            pst.setString(7,medi.getText());
            pst.setString(8,(String)app_doc.getSelectedItem());
            pst.setString(9,problem.getText());
            pst.setString(10,rel_name.getText());
            pst.setString(11,rel_contact.getText());
            pst.executeQuery();
            //////
            
            JOptionPane.showMessageDialog(null, "Patiend Added");
            PreparedStatement pst1 = con.prepareStatement("UPDATE patient SET pat_no = (SELECT patient from id) WHERE pat_name=? AND pat_contact=?");
            //pst1.setString(1, pat_name_txt.getText());
            pst1.setString(1, (String) pat_name_combo.getSelectedItem());
            pst1.setString(2, contact_txt.getText());
            pst1.executeQuery();
            ////
            PreparedStatement pst2 = con.prepareStatement("UPDATE id SET patient = patient+1 ");
            pst2.executeQuery();
            ////
            PreparedStatement pst3 = con.prepareStatement("SELECT pat_no FROM patient WHERE pat_name=? AND pat_contact=?");
            //pst3.setString(1, pat_name_txt.getText());
            pst3.setString(1, (String) pat_name_combo.getSelectedItem());
            pst3.setString(2, contact_txt.getText());
            ResultSet rs3 = pst3.executeQuery();
            if (rs3.next()) {
                counter.setText(rs3.getString(1));
                String sql4 = "Update patient set pat_id = 'PAT'||? WHERE pat_name=? and pat_contact=?";
                PreparedStatement pst4 = con.prepareStatement(sql4);
                pst4.setString(1, counter.getText());
                //pst4.setString(2, pat_name_txt.getText());
                pst4.setString(2, (String) pat_name_combo.getSelectedItem());
                pst4.setString(3, contact_txt.getText());
                
                pst4.executeQuery();

                PreparedStatement pst5 = con.prepareStatement("SELECT pat_id FROM patient WHERE pat_name=? and pat_contact=?");
                //pst5.setString(1, pat_name_txt.getText());
                pst5.setString(1, (String) pat_name_combo.getSelectedItem());
                pst5.setString(2, contact_txt.getText());
                ResultSet rs5 = pst5.executeQuery();
                if (rs5.next()) {
                    pat_id_txt.setText(rs5.getString(1));
                    String sql6 = "Update patient set patient_type='OUT' where pat_id=?";
                    PreparedStatement pst6 = con.prepareStatement(sql6);
                    pst6.setString(1, pat_id_txt.getText());
                    pst6.executeQuery();
                    //Update_table();
                }
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        pat_id_txt.setText("");
        pat_name_combo.setSelectedItem("");
        //pat_name_txt.setText("");
        address_txt.setText("");
        contact_txt.setText("");
        gender.setSelectedItem("");
        app_doc.setSelectedItem("");
        problem.setText("");
        age.setText("");
        ((JTextField)app_date.getDateEditor().getUiComponent()).setText("");
        medi.setText("");
        rel_contact.setText("");
        rel_name.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rel_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rel_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rel_contactActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        close();
        new patient_area().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        close();
        new Admin_Login().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void pat_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_pat_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");
            String temp = (String) pat_name_combo.getSelectedItem();
            String sql = "SELECT * FROM patient WHERE pat_name=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, (String) pat_name_combo.getSelectedItem());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                //pat_name_txt.setText(rs.getString("PAT_NAME"));
                //pat_name_combo.setSelectedItem(rs.getString("PAT_NAME"));
                pat_id_txt.setText(rs.getString("PAT_ID"));
                app_date.setDate(rs.getDate("PAT_DOA"));
                
                contact_txt.setText(rs.getString("PAT_CONTACT"));
                gender.setSelectedItem(rs.getString("GENDER"));
                age.setText(rs.getString("AGE"));
                
                problem.setText(rs.getString("PROBLEM"));
                address_txt.setText(rs.getString("ADDRESS"));
                medi.setText(rs.getString("MEDI"));
                app_doc.setSelectedItem(rs.getString("APP_DOC"));
                
                rel_name.setText(rs.getString("REL_NAME"));
                rel_contact.setText(rs.getString("REL_CONTACT"));
                
                
                //PAT_NO ,PAT_ID,PAT_NAME,PATIENT_TYPE,PAT_DOA,DOD,PAT_CONTACT	GENDER	AGE,ADDRESS,MEDI,APP_DOC,HISTORY,PROBLEM,ROOM	ROOM_TYPE
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_pat_name_comboPopupMenuWillBecomeInvisible

    private void pat_name_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_name_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pat_name_comboActionPerformed

    private void Delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete1ActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to Delete?", "Delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");

                PreparedStatement pst = con.prepareStatement("SELECT * FROM patient WHERE pat_id=?");
                pst.setString(1, pat_id_txt.getText());
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    PreparedStatement pst1 = con.prepareStatement("DELETE FROM patient WHERE pat_id=?");
                    pst1.setString(1, pat_id_txt.getText());

                    pst1.execute();
                    JOptionPane.showMessageDialog(null, "Deleted");
                    pat_name_combo.setSelectedItem("");
                    //Update_table();
                    //Fillcombodoc();

                } else {
                    JOptionPane.showMessageDialog(null, "No Doctor of such Doctor Id is there");
                    JOptionPane.showMessageDialog(null, "Please check the id and retry");
                }

            } catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_Delete1ActionPerformed

    private void contact_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact_txtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )){
            evt.consume();
        }
    }//GEN-LAST:event_contact_txtKeyTyped

    private void rel_contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rel_contactKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )){
            evt.consume();
        }
    }//GEN-LAST:event_rel_contactKeyTyped

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )){
            evt.consume();
        }
    }//GEN-LAST:event_ageKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patient_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patient_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patient_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patient_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patient_out().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel Contact_number;
    private javax.swing.JButton Delete1;
    private javax.swing.JLabel Dob;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel Pat_id;
    private javax.swing.JLabel address;
    private javax.swing.JTextArea address_txt;
    private javax.swing.JTextField age;
    private com.toedter.calendar.JDateChooser app_date;
    private javax.swing.JComboBox app_doc;
    private javax.swing.JTextField contact_txt;
    private javax.swing.JLabel counter;
    private javax.swing.JComboBox gender;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea medi;
    private javax.swing.JTextField pat_id_txt;
    private javax.swing.JLabel pat_name;
    private javax.swing.JComboBox pat_name_combo;
    private javax.swing.JTextArea problem;
    private javax.swing.JTextField rel_contact;
    private javax.swing.JTextField rel_name;
    // End of variables declaration//GEN-END:variables
}
