/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hopital;

/**
 *
 * @author Prabhash
 */
import java.awt.event.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Patient_in extends javax.swing.JFrame {

    /**
     * Creates new form Patient_Entry_Form
     */
    public Patient_in() {
        initComponents();
        Fillcombo();
        Fillcombodoc();
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    private void Fillcombodoc() {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");
            String sql = "SELECT * FROM doctor";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("doc_name");
                appointed_doctor.addItem(name);
            }
        } catch (ClassNotFoundException | SQLException E) {
            JOptionPane.showMessageDialog(null, E);
        }
    }

    private void Fillcombo() {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");
            String sql = "SELECT * FROM patient where PATIENT_TYPE='IN'";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("pat_name");
                pat_name_combo.addItem(name);
            }
        } catch (ClassNotFoundException | SQLException E) {
            JOptionPane.showMessageDialog(null, E);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pat_history = new javax.swing.JLabel();
        problem = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pat_history_txt = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        problem_txt = new javax.swing.JTextArea();
        pat_id_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Jlabel = new javax.swing.JLabel();
        Pat_id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address_txt = new javax.swing.JTextArea();
        pat_name_txt = new javax.swing.JTextField();
        Contact_number = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        pat_name = new javax.swing.JLabel();
        Dob = new javax.swing.JLabel();
        contact_txt = new javax.swing.JTextField();
        pat_age = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox();
        doatxt = new com.toedter.calendar.JDateChooser();
        Add = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rel_name = new javax.swing.JTextField();
        rel_contact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dod = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        appointed_doctor = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        room_type = new javax.swing.JComboBox();
        Room = new javax.swing.JLabel();
        room_txt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pat_name_combo = new javax.swing.JComboBox();
        Delete1 = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        counter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medicine Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        pat_history.setText("Patient History");

        problem.setText("Current Problem");

        pat_history_txt.setColumns(20);
        pat_history_txt.setRows(5);
        jScrollPane2.setViewportView(pat_history_txt);

        problem_txt.setColumns(20);
        problem_txt.setRows(5);
        jScrollPane3.setViewportView(problem_txt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pat_history)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(problem)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(pat_history)
                    .addComponent(problem)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pat_id_txt.setEditable(false);
        pat_id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pat_id_txtActionPerformed(evt);
            }
        });

        jLabel1.setText("Date Of Addmission");

        Jlabel.setText("Gender");

        Pat_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Pat_id.setText("Patient ID");

        address_txt.setColumns(20);
        address_txt.setRows(5);
        jScrollPane1.setViewportView(address_txt);

        Contact_number.setText("Contact Number");

        address.setText("Address");

        pat_name.setText("Patient Name");

        Dob.setText("Age");

        contact_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_txtActionPerformed(evt);
            }
        });
        contact_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contact_txtKeyTyped(evt);
            }
        });

        pat_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pat_ageKeyTyped(evt);
            }
        });

        gender.setEditable(true);
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MALE", "FEMALE", "OTHER" }));

        doatxt.setDateFormatString("dd/MMM/yyyy");

        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/Add-icon.png"))); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/Actions-edit-clear-icon.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relative Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel7.setText("Name");

        jLabel8.setText("Contact");

        rel_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rel_contactActionPerformed(evt);
            }
        });
        rel_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rel_contactKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(rel_contact))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(rel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rel_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rel_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
        );

        jLabel4.setText("Date of Discharge");

        dod.setDateFormatString("dd/MMM/yyyy");

        jLabel3.setText("Doctor Appointed");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Room Details\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel5.setText("Room Type");

        room_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ICU", "OT", "Labour ward", "Patient ward", "Patient ward(A.C)", " ", " ", " " }));
        room_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room_typeActionPerformed(evt);
            }
        });

        Room.setText("Alloted Room");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addGap(19, 19, 19)
                        .addComponent(room_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Room)
                        .addGap(22, 22, 22)
                        .addComponent(room_txt)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(room_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room)
                    .addComponent(room_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete/Update Profile\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel6.setText("Patient Name");

        pat_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                pat_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        pat_name_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pat_name_comboActionPerformed(evt);
            }
        });

        Delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/delete-1-icon.png"))); // NOI18N
        Delete1.setText("Delete");
        Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete1ActionPerformed(evt);
            }
        });

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/App-edit-icon.png"))); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pat_name_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Update)
                        .addGap(18, 18, 18)
                        .addComponent(Delete1)
                        .addGap(16, 16, 16)))
                .addGap(22, 22, 22))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pat_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update)
                    .addComponent(Delete1)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Jlabel)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Pat_id)
                                            .addComponent(address)
                                            .addComponent(pat_name))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pat_id_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pat_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Dob)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1)
                                            .addComponent(Contact_number))))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contact_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(doatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pat_age, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dod, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Add)
                                .addGap(26, 26, 26)
                                .addComponent(Clear))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(appointed_doctor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 155, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(appointed_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pat_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pat_name))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(address)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(contact_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Contact_number))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pat_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Dob)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pat_id)
                                    .addComponent(pat_id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Add)
                            .addComponent(Clear)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(30, 40, 1050, 500);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(800, 10, 70, 20);

        jButton6.setText("Log out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(890, 10, 69, 20);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("X");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(990, 10, 70, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/doctor_female_young.jpg"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 1130, 550);

        counter.setText("jLabel9");
        jPanel3.add(counter);
        counter.setBounds(640, 20, 34, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1127, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1143, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        pat_id_txt.setText("");
        pat_name_txt.setText("");
        address_txt.setText("");
        pat_history_txt.setText("");
        room_txt.setText("");
        contact_txt.setText("");
        gender.setSelectedItem("");
        problem_txt.setText("");
        pat_age.setText("");
        ((JTextField) doatxt.getDateEditor().getUiComponent()).setText("");
        ((JTextField) dod.getDateEditor().getUiComponent()).setText("");
        rel_name.setText("");
        rel_contact.setText("");
        appointed_doctor.setSelectedItem("");
        room_type.setSelectedItem("");
    }//GEN-LAST:event_ClearActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");
            String sql = "insert into patient(pat_name,pat_doa,dod,pat_contact,gender,age,address,app_doc,history,problem,room,room_type,rel_name,rel_contact) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            //pst.setString(1,pat_id_txt.getText());
            pst.setString(1, pat_name_txt.getText());
            pst.setString(2, ((JTextField) doatxt.getDateEditor().getUiComponent()).getText());
            pst.setString(3, ((JTextField) dod.getDateEditor().getUiComponent()).getText());
            pst.setString(4, contact_txt.getText());
            pst.setString(5, (String) gender.getSelectedItem());
            pst.setString(6, pat_age.getText());
            pst.setString(7, address_txt.getText());
            pst.setString(8, (String) appointed_doctor.getSelectedItem());
            pst.setString(9, pat_history_txt.getText());
            pst.setString(10, problem_txt.getText());
            pst.setString(11, room_txt.getText());
            pst.setString(12, (String) room_type.getSelectedItem());
            pst.setString(13, rel_name.getText());
            pst.setString(14, rel_contact.getText());
            pst.executeQuery();
            //////
            
            //////
            JOptionPane.showMessageDialog(null, "Patiend Added");
            PreparedStatement pst1 = con.prepareStatement("UPDATE patient SET pat_no = (SELECT patient from id) WHERE pat_name=? and pat_contact=?");
            pst1.setString(1, pat_name_txt.getText());
            pst1.setString(2, contact_txt.getText());
            pst1.executeQuery();
            ////
            PreparedStatement pst2 = con.prepareStatement("UPDATE id SET patient = patient+1 ");
            pst2.executeQuery();
            ////
            PreparedStatement pst3 = con.prepareStatement("SELECT pat_no FROM patient WHERE pat_name=? and pat_contact=?");
            pst3.setString(1, pat_name_txt.getText());
            pst3.setString(2, contact_txt.getText());
            ResultSet rs3 = pst3.executeQuery();
            if (rs3.next()) {
                counter.setText(rs3.getString(1));
                String sql4 = "Update patient set pat_id = 'PAT'||? WHERE pat_name=? and pat_contact=?";
                PreparedStatement pst4 = con.prepareStatement(sql4);
                pst4.setString(1, counter.getText());
                pst4.setString(2, pat_name_txt.getText());
                pst4.setString(3, contact_txt.getText());
                pst4.executeQuery();

                PreparedStatement pst5 = con.prepareStatement("SELECT pat_id FROM patient WHERE pat_name=? and pat_contact=?");
                pst5.setString(1, pat_name_txt.getText());
                pst5.setString(2, contact_txt.getText());
                ResultSet rs5 = pst5.executeQuery();
                if (rs5.next()) {
                    pat_id_txt.setText(rs5.getString(1));
                    String sql6 = "Update patient set patient_type='IN' where pat_id=?";
                    PreparedStatement pst6 = con.prepareStatement(sql6);
                    pst6.setString(1, pat_id_txt.getText());
                    pst6.executeQuery();
                    //Update_table();
                }
                //JOptionPane.showMessageDialog(null, "Done Everything");
            } else {
                JOptionPane.showMessageDialog(null, "Error Occured!");
            }
        } catch (ClassNotFoundException | SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_AddActionPerformed

    private void pat_id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pat_id_txtActionPerformed

    private void contact_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_txtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        close();
        new patient_area().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        close();
        new Admin_Login().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void rel_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rel_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rel_contactActionPerformed

    private void pat_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_pat_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");
            String temp = (String) pat_name_combo.getSelectedItem();
            String sql = "SELECT * FROM patient WHERE pat_name=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, (String) pat_name_combo.getSelectedItem());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                pat_name_txt.setText(rs.getString("PAT_NAME"));
                pat_id_txt.setText(rs.getString("PAT_ID"));
                //pat_type.setText(rs.getString("PATIENT_TYPE"));
                doatxt.setDate(rs.getDate("PAT_DOA"));
                dod.setDate(rs.getDate("DOD"));
                contact_txt.setText(rs.getString("PAT_CONTACT"));
                //gender.setText(rs.getString("GENDER"));
                gender.setSelectedItem(rs.getString("GENDER"));
                pat_age.setText(rs.getString("AGE"));
                pat_history_txt.setText(rs.getString("HISTORY"));
                problem_txt.setText(rs.getString("PROBLEM"));
                address_txt.setText(rs.getString("ADDRESS"));
                appointed_doctor.setSelectedItem(rs.getString("APP_DOC"));
                room_txt.setText(rs.getString("ROOM"));
                //room_type.setText(rs.getString("ROOM_TYPE"));
                room_type.setSelectedItem(rs.getString("ROOM_TYPE"));
                //room_type.setSelectedItem("ROOM_TYPE");
                rel_name.setText(rs.getString("REL_NAME"));
                rel_contact.setText(rs.getString("REL_CONTACT"));
                
                //app_doc.setSelectedItem(rs.getString("APP_DOC"));
                //app_doc.setSelectedItem("APP_DOC");
                //app_doc.setText(rs.getString("APP_DOC"));
                //PAT_NO ,PAT_ID,PAT_NAME,PATIENT_TYPE,PAT_DOA,DOD,PAT_CONTACT	GENDER	AGE,ADDRESS,MEDI,APP_DOC,HISTORY,PROBLEM,ROOM	ROOM_TYPE
            } 
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_pat_name_comboPopupMenuWillBecomeInvisible

    private void pat_name_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_name_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pat_name_comboActionPerformed

    private void Delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete1ActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to Delete?", "Delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                Class.forName("oracle.jdbc.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");

                PreparedStatement pst = con.prepareStatement("SELECT * FROM patient WHERE pat_id=?");
                pst.setString(1, pat_id_txt.getText());
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    PreparedStatement pst1 = con.prepareStatement("DELETE FROM patient WHERE pat_id=?");
                    pst1.setString(1, pat_id_txt.getText());

                    pst1.execute();
                    JOptionPane.showMessageDialog(null, "Deleted");
                    pat_name_combo.setSelectedItem("");
                    //Update_table();
                    //Fillcombodoc();

                } else {
                    JOptionPane.showMessageDialog(null, "No Doctor of such Doctor Id is there");
                    JOptionPane.showMessageDialog(null, "Please check the id and retry");
                }

            } catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_Delete1ActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "india");

            //String sql = "UPDATE doctor SET(doc_name=?,doc_contact=?,specialzn,doc_dept,doj,address,doc_type,qualification) WHERE doc_id=?";
            String value1 = pat_name_txt.getText();
            String value2 = address_txt.getText();
            String value3 = pat_history_txt.getText();
            String value4 = (String) gender.getSelectedItem();
            String value5 = contact_txt.getText();
            String value6 = pat_age.getText();
            String value7 = problem_txt.getText();
            String value8 = (String) appointed_doctor.getSelectedItem();
            String value9 = (String) room_type.getSelectedItem();
            String value10 = room_txt.getText();
            String value11 = rel_name.getText();
            String value12 = rel_contact.getText();
//doc_name='"+value1+"'
            
            String sql = "UPDATE patient SET PAT_NAME='"+value1+"',PAT_CONTACT='"+value5+"',GENDER='"+value4+"',AGE='"+value6+"',ADDRESS='"+value2+"',APP_DOC='"+value8+"',HISTORY='"+value3+"',PROBLEM='"+value7+"',ROOM='"+value10+"',ROOM_TYPE='"+value9+"',REL_NAME='"+value11+"',REL_CONTACT='"+value12+"' WHERE pat_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, pat_id_txt.getText());
            pst.executeQuery();
            //JOptionPane.showMessageDialog(null, "Be Happy");
            PreparedStatement pst1 = con.prepareStatement("UPDATE patient SET PAT_DOA=?,DOD=? WHERE pat_id=?");
            pst1.setString(1, ((JTextField) doatxt.getDateEditor().getUiComponent()).getText());
            pst1.setString(2, ((JTextField) dod.getDateEditor().getUiComponent()).getText());
            pst1.setString(3, pat_id_txt.getText());
            pst1.executeQuery();
            JOptionPane.showMessageDialog(null, "Updated");
//PAT_NAME'"+value1+"',PATIENT_TYPE,PAT_DOA'"+value1+"',DOD'"+value1+"',PAT_CONTACT'"+value1+"',GENDER'"+value1+"',AGE'"+value1+"',ADDRESS'"+value1+"',APP_DOC'"+value1+"',HISTORY'"+value1+"',PROBLEM'"+value1+"',ROOM'"+value1+"',ROOM_TYPE'"+value1+"',REL_NAME'"+value1+"',REL_CONTACT'"+value1+"'            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void room_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room_typeActionPerformed

    private void rel_contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rel_contactKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )){
            evt.consume();
        }
    }//GEN-LAST:event_rel_contactKeyTyped

    private void pat_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pat_ageKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )){
            evt.consume();
        }
    }//GEN-LAST:event_pat_ageKeyTyped

    private void contact_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact_txtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) )){
            evt.consume();
        }
    }//GEN-LAST:event_contact_txtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Clear;
    private javax.swing.JLabel Contact_number;
    private javax.swing.JButton Delete1;
    private javax.swing.JLabel Dob;
    private javax.swing.JLabel Jlabel;
    private javax.swing.JLabel Pat_id;
    private javax.swing.JLabel Room;
    private javax.swing.JButton Update;
    private javax.swing.JLabel address;
    private javax.swing.JTextArea address_txt;
    private javax.swing.JComboBox appointed_doctor;
    private javax.swing.JTextField contact_txt;
    private javax.swing.JLabel counter;
    private com.toedter.calendar.JDateChooser doatxt;
    private com.toedter.calendar.JDateChooser dod;
    private javax.swing.JComboBox gender;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField pat_age;
    private javax.swing.JLabel pat_history;
    private javax.swing.JTextArea pat_history_txt;
    private javax.swing.JTextField pat_id_txt;
    private javax.swing.JLabel pat_name;
    private javax.swing.JComboBox pat_name_combo;
    private javax.swing.JTextField pat_name_txt;
    private javax.swing.JLabel problem;
    private javax.swing.JTextArea problem_txt;
    private javax.swing.JTextField rel_contact;
    private javax.swing.JTextField rel_name;
    private javax.swing.JTextField room_txt;
    private javax.swing.JComboBox room_type;
    // End of variables declaration//GEN-END:variables
}
